[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "^0.2", default-features = false }
wasm-bindgen-futures = { version = "^0.4", default-features = false }

windowing = { path = "../.." }